---
- name: Router1 FRR Configure
  hosts: router1
  become: true
  
  tasks:
    - name: Copy zebra.conf
      copy:
        src: ../../config/ospfd1
        dest: /vagrant/config/ospfd1

    - name: Cat ospfd.conf
      shell: cat /vagrant/config/ospfd1 > /etc/frr/ospfd.conf
    
    - name: OSPF yes
      shell: sed -i 's/ospfd=no/ospfd=yes/' /etc/frr/daemons

    - name: Restart FRR
      systemd:
        name: frr
        state: restarted

- name: Router2 FRR Configure
  hosts: router2
  become: true
  
  tasks:
    - name: Copy zebra.conf
      copy:
        src: ../../config/ospfd2
        dest: /vagrant/config/ospfd2

    - name: Cat zebra.conf
      shell: cat /vagrant/config/ospfd2 > /etc/frr/ospfd.conf

    - name: OSPF yes
      shell: sed -i 's/ospfd=no/ospfd=yes/' /etc/frr/daemons

    - name: Restart FRR
      systemd:
        name: frr
        state: restarted
      
- name: Router3 FRR Configure
  hosts: router3
  become: true
  
  tasks:
    - name: Copy zebra.conf
      copy:
        src: ../../config/ospfd3
        dest: /vagrant/config/ospfd3

    - name: Cat zebra.conf
      shell: cat /vagrant/config/ospfd3 > /etc/frr/ospfd.conf
 
    - name: OSPF yes
      shell: sed -i 's/ospfd=no/ospfd=yes/' /etc/frr/daemons

    - name: Restart FRR
      systemd:
        name: frr
        state: restarted
 