---
- name: Install package
  hosts: all
  become: true

  tasks:
    - name: Install repo FRR
      shell: "/vagrant/scripts/frr.sh"
    
    - name: Install user package
      yum:
        name:
          - mc
          - vim
          - tcpdump
          - frr
          - frr-pythontools
        state: latest

    - name: Enable forwarding ipv4
      shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf

    - name: Disable forwarding ipv4 for eth1
      shell: echo "net.ipv4.conf.eth1.rp_filter = 0" >> /etc/sysctl.conf

    - name: Disable forwarding ipv4 for eth2
      shell: echo "net.ipv4.conf.eth2.rp_filter = 0" >> /etc/sysctl.conf
    
    # - name: Restrat network
    #   systemd:
    #     name: NetworkManager
    #     state: restarted
    #   tags:
    #     - forwarding

    - name: Restrat network
      systemd:
        name: network
        state: restarted

    - name: Start frr service
      systemd:
        name: frr
        state: started

    - name: Enable frr service
      systemd:
        name: frr
        enabled: yes
